FROM mcr.microsoft.com/oss/go/microsoft/golang:1.20-fips-cbl-mariner2.0 AS builder
WORKDIR /source

COPY go.mod .
RUN go mod download

COPY . .
RUN go build -o /app/program .

WORKDIR /app
ENTRYPOINT ["./program"]
