FROM mcr.microsoft.com/oss/go/microsoft/golang:1.20-windowsservercore-ltsc2022 AS builder
WORKDIR /source

ENV GOEXPERIMENT=cngcrypto

COPY go.mod .
RUN go mod download

COPY . .
RUN go build -o /app/program.exe .

WORKDIR /app
ENTRYPOINT ["program"]
